### ISSUE TITLE
为什么 font-family 是 -apple-system-font，而不是 -apple-system ?

### ISSUE THREAD

**Issue by liuzhuan** [Tencent/weui#759]
在 [Using the System Font in Web Content](https://webkit.org/blog/3709/using-the-system-font-in-web-content/) 中，*Myles Maxfield* 曾提到 `font-family: -apple-system;` 的写法。它的作用是，在 iOS 9 和 OS X 10.11 中，将使用 Apple 新字体，*San Francisco*。在其他不支持 `-apple-system` 的平台，浏览器会自动回退使用字体栈下一个字体。

在 [System Font Stack](https://css-tricks.com/snippets/css/system-font-stack/) 中，也有 Github 字体栈的写法：

```css
body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
}
```

同样是 `-apple-system` 的字体。

而 WeUI 目前使用的是 `font-family: -apple-system-font`。这是有其他特殊考虑，还是笔误呢？
