### ISSUE TITLE
2.4 Picker的深色模式好丑，是bug还就是这样的？

### ISSUE THREAD

**Issue by heii** [Tencent/weui#856]
![weui io_(iPhone X)](https://user-images.githubusercontent.com/4813829/85245029-f48a4900-b478-11ea-8d96-f3c7e8901fca.png)

**Comment by BearJ** [comment]
@heii 的确是bug，目前可以先加上这段css来fix：
```css
@media (prefers-color-scheme: dark) {
  body:not([data-weui-theme='light']) .weui-picker__mask {
    background-image: linear-gradient(180deg, rgba(25, 25, 25, 0.95), rgba(25, 25, 25, 0.6)), linear-gradient(0deg, rgba(25, 25, 25, 0.95), rgba(25, 25, 25, 0.6));
  }
}
```
